#!/usr/bin/env python3

import argparse
import os
import sys
from pathlib import Path


def random_value(size: int) -> int:
    return int.from_bytes(os.urandom(size), "little")


def u32(value: int) -> str:
    return f"0x{value:08X}u"


def u64(value: int) -> str:
    return f"0x{value:016X}ull"


def u8(value: int) -> str:
    return f"0x{value:02X}u"


def build_config() -> str:
    domain_id = random_value(4)
    magic = random_value(4)
    secret = random_value(8)
    secret_mask = random_value(1)
    primary_tag = random_value(8)
    secondary_tag = random_value(8)

    return f"""#pragma once

#include <ripstop/Codec.h>

#include <cstdint>
#include <string_view>

// Generated by tools/generate_config.py.
// Rotating any value below invalidates assets encoded with the old config.
namespace ripstop_config {{

inline constexpr std::uint32_t ripstopDomainId = {u32(domain_id)};
inline constexpr std::uint32_t ripstopMagic = {u32(magic)};
inline constexpr std::uint16_t kDefaultAssetVersion = 1u;
inline constexpr std::uint64_t tagPrimaryAsset = {u64(primary_tag)};
inline constexpr std::uint64_t tagSecondaryAsset = {u64(secondary_tag)};
inline constexpr auto kProjectSecret =
    ripstop::codec::utils::make_obfuscated_secret<{u64(secret)}, {u8(secret_mask)}>();

[[nodiscard]] inline ripstop::codec::ProjectOptions MakeProjectOptions() {{
    return {{
        .magic = ripstopMagic,
        .domain_id = ripstopDomainId,
        .project_secret = kProjectSecret.resolve(),
    }};
}}

[[nodiscard]] inline constexpr std::uint64_t HashContextString(std::string_view value) {{
    return ripstop::codec::utils::hash_string(value);
}}

[[nodiscard]] inline constexpr std::uint64_t HashContextUint64(std::uint64_t value) {{
    return ripstop::codec::utils::hash_uint64(value);
}}

[[nodiscard]] inline constexpr ripstop::codec::AssetOptions MakeAssetOptions(
    std::uint64_t formatTag,
    std::uint64_t contextSeed = 0,
    std::uint64_t nonce = 0,
    std::uint16_t assetVersion = kDefaultAssetVersion,
    ripstop::codec::IdentityType identityType = ripstop::codec::IdentityType::None,
    std::uint8_t paddingSize = 0,
    bool compress = true,
    bool scramble = true) {{
    return {{
        .format_tag = formatTag,
        .context_seed = contextSeed,
        .nonce = nonce,
        .asset_version = assetVersion,
        .identity_type = identityType,
        .padding_size = paddingSize,
        .compress = compress,
        .scramble = scramble,
    }};
}}

}} // namespace ripstop_config
"""


def main() -> int:
    parser = argparse.ArgumentParser(
        description="Generate an advanced randomized RipStop_Config.h file."
    )
    parser.add_argument("--out", type=Path, default=Path("RipStop_Config.h"))
    parser.add_argument("--force", action="store_true", help="Overwrite an existing config.")
    args = parser.parse_args()

    if args.out.exists() and not args.force:
        sys.stderr.write(
            f"Refusing to overwrite {args.out}. Existing values are an asset compatibility "
            "boundary; pass --force only when rotation is intentional.\n"
        )
        return 2

    args.out.parent.mkdir(parents=True, exist_ok=True)
    args.out.write_text(build_config(), encoding="utf-8")
    sys.stdout.write(f"Wrote {args.out}\n")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
