#!/usr/bin/env python3

import argparse
import sys
from pathlib import Path

import os


def random_u32() -> int:
    return int.from_bytes(os.urandom(4), "little")


def random_u64() -> int:
    return int.from_bytes(os.urandom(8), "little")


def random_u8() -> int:
    return os.urandom(1)[0]


def fmt_u32(value: int) -> str:
    return f"0x{value:08X}u"


def fmt_u64(value: int) -> str:
    return f"0x{value:016X}ull"


def fmt_u8(value: int) -> str:
    return f"0x{value:02X}u"


def build_config() -> str:
    domain_id = random_u32()
    magic = random_u32()
    xor_mask = random_u8()
    secret = random_u64()
    primary_tag = random_u64()
    secondary_tag = random_u64()

    return f"""#pragma once

#include <cstdint>
#include <memory>
#include <string_view>

// Generated by tools/generate_config.py.
// Regenerate this file whenever you want to rotate project-specific codec values.

// 1. Error Output

#define RIPSTOP_ERROR_XOR {fmt_u32(random_u32())}
#define RIPSTOP_HARDEN_ERRORS 1

#include <ripstop/Codec.h>

namespace ripstop_config {{

// 2. Security Lifecycle Hooks

class ExampleSecurityPolicy final : public ::ripstop::codec::ISecurityPolicy {{
public:
    bool PreDecode(std::span<const std::uint8_t> encodedData) const override {{
        (void)(encodedData);
        return true;
    }}

    void OnScrambleState(std::uint64_t& state) const override {{
        (void)(state);
    }}

    bool PostDescramble(std::span<std::uint8_t> decodedBuffer) const override {{
        (void)(decodedBuffer);
        return true;
    }}

    void OnTamper(::ripstop::codec::ErrorCode code) const override {{
        (void)(code);
    }}

    void OnError(::ripstop::codec::ErrorCode code) const override {{
        (void)(code);
    }}
}};

// 2. Asset Identity & Policy

inline constexpr std::uint32_t ripstopDomainId = {fmt_u32(domain_id)};
inline constexpr std::uint32_t ripstopMagic = {fmt_u32(magic)};
inline constexpr std::uint16_t kDefaultAssetVersion = 1u;

inline constexpr std::uint64_t tagPrimaryAsset = {fmt_u64(primary_tag)};
inline constexpr std::uint64_t tagSecondaryAsset = {fmt_u64(secondary_tag)};

// 3. Project Secret

inline constexpr auto kProjectSecret =
    ::ripstop::codec::utils::make_obfuscated_secret<{fmt_u64(secret)}, {fmt_u8(xor_mask)}>();

inline constexpr std::uint64_t HashContextString(std::string_view value) {{
    return ::ripstop::codec::utils::hash_string(value);
}}

inline constexpr std::uint64_t HashContextUint64(std::uint64_t value) {{
    return ::ripstop::codec::utils::hash_uint64(value);
}}

inline ::ripstop::codec::ProjectOptions MakeProjectOptions() {{
    return {{
        .magic = ripstopMagic,
        .domain_id = ripstopDomainId,
        .project_secret = kProjectSecret.resolve(),
        .scramble_id = ::ripstop::codec::Header::ScrambleSplitMix64,
        .scrambler = nullptr,
        .policy = std::make_shared<ExampleSecurityPolicy>(),
    }};
}}

inline constexpr ::ripstop::codec::AssetOptions MakeAssetOptions(
    std::uint64_t formatTag,
    std::uint64_t contextSeed = 0,
    std::uint64_t nonce = 0,
    std::uint16_t assetVersion = kDefaultAssetVersion,
    ::ripstop::codec::IdentityType identityType = ::ripstop::codec::IdentityType::None,
    std::uint8_t paddingSize = 0,
    bool compress = true,
    bool scramble = true) {{
    // Leave nonce at 0 for deterministic builds. Set it to a timestamp or random value
    // when you want each encode to produce a different binary blob.
    return {{
        .format_tag = formatTag,
        .context_seed = contextSeed,
        .nonce = nonce,
        .asset_version = assetVersion,
        .identity_type = identityType,
        .padding_size = paddingSize,
        .compress = compress,
        .scramble = scramble,
    }};
}}

}} // namespace ripstop_config
"""


def main() -> int:
    parser = argparse.ArgumentParser(description="Generate a randomized RipStop_Config.h file.")
    parser.add_argument("--out", type=Path, help="Output file path. Defaults to ./RipStop_Config.h.")
    args = parser.parse_args()

    content = build_config()
    output_path = args.out if args.out is not None else Path("RipStop_Config.h")

    output_path.parent.mkdir(parents=True, exist_ok=True)
    output_path.write_text(content, encoding="utf-8")
    sys.stdout.write(f"Wrote {output_path}\n")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
